apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-gateway.eppName" . }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: epp
spec:
  type: ClusterIP
  selector:
    {{- include "inference-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: epp
  ports:
    - name: grpc-ext-proc
      protocol: TCP
      port: 9002
      targetPort: grpc-ext-proc
    - name: grpc-health
      protocol: TCP
      port: 9003
      targetPort: grpc-health
    - name: http-metrics
      protocol: TCP
      port: 9090
      targetPort: http-metrics
