{{- if (index .Values "envoy-gateway").enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "networking-layer.gatewayName" . }}
  labels:
    {{- include "networking-layer.labels" . | nindent 4 }}
  {{- if or (and .Values.tls.enabled .Values.tls.certManager.enabled) .Values.gateway.annotations }}
  annotations:
    {{- if and .Values.tls.enabled .Values.tls.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.certManager.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ include "networking-layer.gatewayClassName" . }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- if .Values.gateway.hostname }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
    {{- if .Values.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      {{- if .Values.gateway.hostname }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.tls.secretName | default (printf "%s-tls" (include "networking-layer.fullname" .)) }}
            kind: Secret
    {{- end }}
{{- end }}
