{{- if .Values.envoyGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "networking-layer.gatewayClassName" . }}
  labels:
    {{- include "networking-layer.labels" . | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  {{- if .Values.envoyGateway.preserveRequestId }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ include "networking-layer.fullname" . }}-proxy-config
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
