{{- if .Values.gateway.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Release.Name }}-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: {{ .Values.gateway.service.type }}
{{- with .Values.gateway.service.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Release.Name }}-proxy-config
    namespace: {{ .Release.Namespace }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
{{- if and .Values.gateway.listeners.https.enabled .Values.gateway.listeners.https.certManager.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.listeners.https.certManager.clusterIssuer }}
{{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
{{- if .Values.gateway.listeners.http.enabled }}
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listeners.http.port }}
{{- end }}
{{- if .Values.gateway.listeners.https.enabled }}
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.listeners.https.port }}
{{- if .Values.gateway.listeners.https.hostname }}
      hostname: {{ .Values.gateway.listeners.https.hostname | quote }}
{{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.listeners.https.certificateRef }}
{{- end }}
{{- end }}
